table F_TRANSACCIONES
	lineageTag: c03b14be-55f1-4461-8418-8a9104840901

	column codigo_operacion
		dataType: string
		lineageTag: 73c2d58f-0b17-484d-a56e-5e3d420d78ba
		summarizeBy: none
		sourceColumn: codigo_operacion

		annotation SummarizationSetBy = Automatic

	column fecha_venta
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3508c669-6032-4351-ba4f-4b0fa7ee0dc7
		summarizeBy: none
		sourceColumn: fecha_venta

		variation Variación
			isDefault
			relationship: 8a78d009-ccf7-40c2-b02c-9a69a146aa9e
			defaultHierarchy: LocalDateTable_a442df3c-cb0b-4df3-b4cc-61f7446ec9d2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column codigo_producto
		dataType: int64
		formatString: 0
		lineageTag: 5d247006-5ba7-43da-88a8-3a522b59864c
		summarizeBy: sum
		sourceColumn: codigo_producto

		annotation SummarizationSetBy = Automatic

	column descripcion_producto
		dataType: string
		lineageTag: f21bc92a-accd-4751-80e5-759e51b6aed8
		summarizeBy: none
		sourceColumn: descripcion_producto

		annotation SummarizationSetBy = Automatic

	column categoria_producto
		dataType: string
		lineageTag: 490fa21e-2cc7-435f-a398-a597a4f6d29c
		summarizeBy: none
		sourceColumn: categoria_producto

		annotation SummarizationSetBy = Automatic

	column cantidad
		dataType: int64
		formatString: 0
		lineageTag: 834a1b24-0530-4559-955b-55cae1b46a4a
		summarizeBy: sum
		sourceColumn: cantidad

		annotation SummarizationSetBy = Automatic

	column precio_unitario_venta
		dataType: double
		lineageTag: 94d14257-fe49-40c6-9efa-d20a2b9a24b5
		summarizeBy: sum
		sourceColumn: precio_unitario_venta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column porcentaje_descuento
		dataType: double
		lineageTag: c2b93cd7-8a7f-4acb-9fef-aeacc9cd0755
		summarizeBy: sum
		sourceColumn: porcentaje_descuento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_de_la_venta
		dataType: double
		lineageTag: bef600cd-556b-4cc7-812d-e53f104f0d05
		summarizeBy: sum
		sourceColumn: total_de_la_venta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column codigo_moneda
		dataType: string
		lineageTag: b7f29e2b-f401-462c-9f2a-c0748c1b0868
		summarizeBy: none
		sourceColumn: codigo_moneda

		annotation SummarizationSetBy = Automatic

	column canal_de_venta
		dataType: string
		lineageTag: f160677d-9a74-4ec3-aadf-1e9115c98fbc
		summarizeBy: none
		sourceColumn: canal_de_venta

		annotation SummarizationSetBy = Automatic

	column codigo_cliente
		dataType: string
		lineageTag: 660c422b-2415-4b18-bed6-b2bd2dcca7ac
		summarizeBy: none
		sourceColumn: codigo_cliente

		annotation SummarizationSetBy = Automatic

	partition F_TRANSACCIONES = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\JP\Downloads\Ventas_export_legacy.xlsx"), null, true),
				    VENTAS_EXPORT_Sheet = Origen{[Item="VENTAS_EXPORT",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(VENTAS_EXPORT_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"COD_OP", type text}, {"COD_CLI", type text}, {"NOM_CLI", type text}, {"MAIL_CLI", type text}, {"TEL_CLI", type text}, {"CIU_CLI", type text}, {"PROV_CLI", type text}, {"SEG_CLI", type text}, {"FLG_ACT", type text}, {"F_ALTA_CLI", type date}, {"F_VTA", type datetime}, {"COD_PROD", Int64.Type}, {"DESC_PROD", type text}, {"RUBRO_PROD", type text}, {"CANT", Int64.Type}, {"PU_VTA", type number}, {"DTO_PCT", type number}, {"TOT_VTA", type number}, {"COD_MON", type text}, {"CANAL_VTA", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"COD_OP", "codigo_operacion"}, {"COD_CLI", "codigo_cliente"}, {"NOM_CLI", "nombre_cliente"}, {"MAIL_CLI", "email_cliente"}, {"TEL_CLI", "telefono_cliente"}, {"CIU_CLI", "ciudad_cliente"}, {"PROV_CLI", "provincia_cliente"}, {"SEG_CLI", "segmentacion_cliente"}, {"FLG_ACT", "bandera_activo"}, {"F_ALTA_CLI", "fecha_alta_cliente"}, {"F_VTA", "fecha_venta"}, {"COD_PROD", "codigo_producto"}, {"DESC_PROD", "descripcion_producto"}, {"RUBRO_PROD", "categoria_producto"}, {"CANT", "cantidad"}, {"PU_VTA", "precio_unitario_venta"}, {"DTO_PCT", "porcentaje_descuento"}, {"TOT_VTA", "total_de_la_venta"}, {"COD_MON", "codigo_moneda"}, {"CANAL_VTA", "canal_de_venta"}}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"porcentaje_descuento", Percentage.Type}}),
				    #"Duplicados quitados" = Table.Distinct(#"Tipo cambiado1", {"codigo_operacion"}),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Duplicados quitados", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Filas en blanco eliminadas",null,"n/a",Replacer.ReplaceValue,{"email_cliente"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado",null,"n/a",Replacer.ReplaceValue,{"telefono_cliente"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1",null,"n/a",Replacer.ReplaceValue,{"ciudad_cliente"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Valor reemplazado2",{{"fecha_venta", type date}}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Tipo cambiado2",null,0,Replacer.ReplaceValue,{"porcentaje_descuento"}),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Valor reemplazado3",{{"porcentaje_descuento", Percentage.Type}}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Tipo cambiado3",null,0,Replacer.ReplaceValue,{"total_de_la_venta"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Valor reemplazado4",{"nombre_cliente", "email_cliente", "telefono_cliente", "ciudad_cliente", "provincia_cliente", "segmentacion_cliente", "bandera_activo", "fecha_alta_cliente"}),
				    #"Duplicados quitados1" = Table.Distinct(#"Columnas quitadas")
				in
				    #"Duplicados quitados1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

